const $ = (id) => document.getElementById(id);
const state = { file: null, result: null, jobId: null };
const stages = ['Storage acquisition', 'Fragment extraction', 'Fragment DNA generation', 'Artifact classification', 'Fragment relationship analysis', 'Reconstruction', 'Integrity verification'];

function humanBytes(bytes) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function esc(value) { return String(value).replace(/[&<>\"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', "'": '&#039;' }[char])); }
function setStage(stage, progress) { $('analysisStage').textContent = stage; $('progressValue').textContent = `${progress}%`; $('progressBar').style.width = `${progress}%`; $('stageList').innerHTML = stages.map((name) => `<div class="analysis-stage ${name === stage ? 'current' : stages.indexOf(name) < stages.indexOf(stage) ? 'done' : ''}"><span>${stages.indexOf(name) < stages.indexOf(stage) ? '✓' : name === stage ? '●' : '○'}</span>${name}</div>`).join(''); }

function render(result) {
  state.result = result;
  $('headerCase').textContent = result.caseId;
  $('casePill').textContent = `${result.caseId} · SAVED`;
  $('caseTitle').textContent = result.filename;
  $('artifactCount').textContent = result.artifacts.length;
  $('recoverableCount').textContent = result.artifacts.filter((a) => a.status === 'recoverable').length;
  $('partialCount').textContent = result.artifacts.filter((a) => a.status !== 'recoverable').length;
  $('integrity').textContent = `${result.overallIntegrity}%`;
  $('artifactSub').textContent = `${result.fragmentCount} fragments mapped`;
  $('clusterSub').textContent = `${result.unresolvedClusters} unresolved clusters`;
  $('queueLabel').textContent = `${result.artifacts.length} artifacts · ${humanBytes(result.recoverableBytes)} recoverable volume`;
  $('reportLink').href = `/api/cases/${result.caseId}/report`;
  $('reportLink').classList.remove('disabled');
  $('artifactList').innerHTML = result.artifacts.map((artifact, index) => `<article class="artifact-row" data-artifact="${index}"><div class="artifact-icon ${artifact.type}">${artifact.type === 'photo' ? '▧' : artifact.type === 'document' ? '▤' : artifact.type === 'database' ? '◉' : '◇'}</div><div class="artifact-main"><strong>${esc(artifact.name)}</strong><span><b class="priority ${artifact.priority}">${artifact.priority}</b> ${artifact.status} · offset ${artifact.offset} · ${humanBytes(artifact.size)}</span><small>${esc(artifact.decision || 'manual investigation')}</small></div><div class="artifact-score"><strong>${artifact.integrity}%</strong><span>integrity</span><div class="score-bar"><i style="width:${artifact.integrity}%"></i></div><small>${artifact.mlScore}% ML rank</small></div><div class="artifact-actions">${artifact.viewableUrl || artifact.reconstructedUrl ? `<a href="${artifact.viewableUrl || artifact.reconstructedUrl}?preview=1" target="_blank" title="View supported recovered file" onclick="event.stopPropagation()">◉</a>` : ''}</div></article>`).join('');
  document.querySelectorAll('[data-artifact]').forEach((row) => row.addEventListener('click', () => showArtifact(result.artifacts[Number(row.dataset.artifact)])));
  $('recommendations').innerHTML = result.recommendations.map((item) => `<p>${esc(item)}</p>`).join('');
  const edges = result.fragmentGraph?.edges || [];
  $('graph').innerHTML = edges.length ? `<div class="graph-meta">${result.fragmentGraph.nodes.length} nodes · ${edges.length} relationships derived from storage offsets</div>${edges.map((edge) => `<div class="edge"><b>${edge.from}</b><span></span><b>${edge.to}</b><small>${edge.gap} byte gap · ${edge.relationship}</small></div>`).join('')}` : '<div class="empty-state"><span>⌘</span><p>No adjacent fragment relationships were found in this case.</p></div>';
  $('answer').innerHTML = '<span>◇</span><p>Ask a question about the analyzed evidence.</p>';
  showArtifact(result.artifacts.find((artifact) => artifact.type === 'photo') || result.artifacts[0]);
}
function selectFile(file) { state.file = file; $('startBtn').disabled = !file; $('uploadTitle').textContent = file ? file.name : 'Drop evidence here'; $('uploadHint').innerHTML = file ? '<u>Choose a different file</u>' : 'or <u>browse files</u>'; $('uploadMeta').textContent = file ? `${humanBytes(file.size)} · ready for forensic analysis` : 'Images, disk dumps, PDFs and binaries · max 25 MB'; $('selectionStatus').textContent = file ? 'Evidence ready' : 'No evidence selected'; }
function showArtifact(artifact) { const detail = $('artifactDetail'); const displayUrl = artifact.viewableUrl || artifact.reconstructedUrl; const preview = displayUrl && artifact.type === 'photo' ? `<img src="${displayUrl}?preview=1" alt="Supported recovered image preview" onerror="this.replaceWith(Object.assign(document.createElement('span'), {textContent:'The recovered image cannot be decoded from the available bytes.'}))">` : `<span>${artifact.type.toUpperCase()}<br>${humanBytes(artifact.size)}</span>`; const reconstruction = artifact.reconstruction || { rawBytes: artifact.size, reconstructedBytes: artifact.size, removedBytes: 0 }; detail.innerHTML = `<div class="detail-head"><div><p class="eyebrow">ARTIFACT INSPECTOR</p><h3>${esc(artifact.name)}</h3></div><button class="detail-close" id="closeDetail">×</button></div><div class="detail-grid"><div class="preview-box">${preview}</div><div class="detail-data"><div><span>Type</span><strong>${esc(artifact.type)}</strong></div><div><span>Recovery</span><strong>${artifact.mlScore}%</strong></div><div><span>Integrity</span><strong>${artifact.integrity}%</strong></div><div><span>Fragments</span><strong>${artifact.missingClusters.length + 1}</strong></div><div><span>Corruption</span><strong>${artifact.missingClusters.length} region(s)</strong></div><div><span>Supported output</span><strong>${artifact.viewableUrl ? 'PNG ready' : 'Unavailable'}</strong></div></div><div class="detail-evidence"><b>Evidence:</b> ${artifact.evidence.map(esc).join(' · ')}<br><b>Reconstruction:</b> ${reconstruction.removedBytes} bytes of detected cluster padding removed.<br>${artifact.viewableUrl ? `<a href="${artifact.viewableUrl}">Download supported PNG</a> · ` : ''}${artifact.reconstructedUrl ? `<a href="${artifact.reconstructedUrl}">Download reconstructed file</a> · ` : ''}${artifact.recoveredUrl ? `<a href="${artifact.recoveredUrl}">Download raw carve</a>` : ''}</div></div>`; detail.classList.remove('hidden'); $('closeDetail').addEventListener('click', () => detail.classList.add('hidden')); detail.scrollIntoView({ behavior: 'smooth', block: 'start' }); }

async function waitForJob(jobId) { for (;;) { const response = await fetch(`/api/jobs/${jobId}`); const job = await response.json(); setStage(job.stage, job.progress); if (job.status === 'complete') return job.result; if (job.status === 'error') throw new Error(job.error); await new Promise((resolve) => setTimeout(resolve, 120)); } }
async function startAnalysis(file) { if (!file) return; state.file = file; $('analysisPanel').classList.remove('hidden'); $('startBtn').disabled = true; $('selectionStatus').textContent = 'Analysis running'; setStage('Queued', 0); try { const response = await fetch('/api/jobs', { method: 'POST', headers: { 'X-Filename': file.name }, body: await file.arrayBuffer() }); const job = await response.json(); if (!response.ok) throw new Error(job.error); const result = await waitForJob(job.jobId); $('selectionStatus').textContent = 'Analysis complete'; render(result); } catch (error) { $('selectionStatus').textContent = 'Analysis failed'; alert(`Analysis failed: ${error.message}`); } finally { $('startBtn').disabled = false; } }
async function runDemo() { $('analysisPanel').classList.remove('hidden'); setStage('Synthetic case', 100); $('selectionStatus').textContent = 'Synthetic case loaded'; const response = await fetch('/api/demo'); const result = await response.json(); render(result); }
async function ask() { if (!state.result) return; const question = $('questionInput').value.trim(); if (!question) return; $('answer').innerHTML = '<span class="spin">◌</span><p>Searching evidence sources...</p>'; const response = await fetch('/api/ask', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ caseId: state.result.caseId, question }) }); const result = await response.json(); $('answer').innerHTML = `<p>${esc(result.answer)}</p><div class="source-list">${result.sources.map((source) => `<span>${esc(source.name)} · ${source.mlScore}%</span>`).join('')}</div>`; }

$('startBtn').addEventListener('click', () => startAnalysis(state.file)); $('demoBtn').addEventListener('click', runDemo); $('askBtn').addEventListener('click', ask); $('questionInput').addEventListener('keydown', (event) => { if (event.key === 'Enter') ask(); }); $('fileInput').addEventListener('change', (event) => selectFile(event.target.files[0])); $('dropzone').addEventListener('click', () => $('fileInput').click()); $('dropzone').addEventListener('dragover', (event) => { event.preventDefault(); $('dropzone').classList.add('dragging'); }); $('dropzone').addEventListener('dragleave', () => $('dropzone').classList.remove('dragging')); $('dropzone').addEventListener('drop', (event) => { event.preventDefault(); $('dropzone').classList.remove('dragging'); selectFile(event.dataTransfer.files[0]); }); document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => document.getElementById(button.dataset.scroll).scrollIntoView({ behavior: 'smooth' })));
